CREATE DATABASE datacenterhrplus;

CREATE TABLE `datacenterhrplus`.`Candidatos` ( `Id` INT NOT NULL AUTO_INCREMENT , `nombre` TEXT NULL , `apellido` TEXT NULL , `cedula` INT NULL , `telefono` INT NULL , `correo` TEXT NULL , `direccion` TEXT NULL , `perfil` TEXT NULL , `sobreMi` TEXT NULL , `nEU` TEXT NULL , `fEU` TEXT NULL , `nEP` TEXT NULL , `fEP` TEXT NULL , `nEA` TEXT NULL , `fEA` TEXT NULL , `nIU` TEXT NULL , `tIU` TEXT NULL , `nIP` TEXT NULL , `tIP` TEXT NULL , `nIA` TEXT NULL , `tIA` TEXT NULL , `idiomaN` TEXT NULL , `idiomaEP` TEXT NULL , `idiomaES` TEXT NULL , `conocimientos` TEXT NULL , `intereses` TEXT NULL , `habilidades` TEXT NULL , PRIMARY KEY (`Id`)) ENGINE = InnoDB;


INSERT INTO `datacenterhrplus`.`Candidatos`(`Id`, `nombre`, `apellido`, `cedula`, `telefono`, `correo`, `direccion`, `perfil`, `sobreMi`, `nEU`, `fEU`, `nEP`, `fEP`, `nEA`, `fEA`, `nIU`, `tIU`, `nIP`, `tIP`, `nIA`, `tIA`, `idiomaN`, `idiomaEP`, `idiomaES`, `conocimientos`, `intereses`, `habilidades`) VALUES ('','Julian','Avella',123456789,3133692581,'julian@gmail.com','calle falsa 123','Ingenierio de software','Soy estudiante','Coca cola','Desarrollar','Gobierno nacional','Desarrollar','Nasa','Desarrollar','Uniempri','Ingeniero','Sena','Adminis','Parroco','Bachi','Español','Ingles','Frances','Sotfware','Muchos','Ser yo');
INSERT INTO `datacenterhrplus`.`Candidatos`(`Id`, `nombre`, `apellido`, `cedula`, `telefono`, `correo`, `direccion`, `perfil`, `sobreMi`, `nEU`, `fEU`, `nEP`, `fEP`, `nEA`, `fEA`, `nIU`, `tIU`, `nIP`, `tIP`, `nIA`, `tIA`, `idiomaN`, `idiomaEP`, `idiomaES`, `conocimientos`, `intereses`, `habilidades`) VALUES ('','Richard','Deiby',987654321,3133692581,'richard@gmail.com','calle falsa 456','Ingenierio de software','Soy estudiante','Coca cola','Desarrollar','Gobierno nacional','Desarrollar','Nasa','Desarrollar','Uniempri','Ingeniero','Sena','Adminis','Parroco','Bachi','Español','Ingles','Frances','Sotfware','Muchos','Ser yo');

/*INSERT INTO `datacenterhrplus`.`Candidatos`(`Id`, `nombre`, `apellido`, `cedula`, `telefono`, `correo`, `direccion`, `perfil`, `sobreMi`, `nEU`, `fEU`, `nEP`, `fEP`, `nEA`, `fEA`, `nIU`, `tIU`, `nIP`, `tIP`, `nIA`, `tIA`, `idiomaN`, `idiomaEP`, `idiomaES`, `conocimientos`, `intereses`, `habilidades`) VALUES (1,'Julian','Avella',123456789,31336925,'julian@gmail.com','calle falsa 123','Ingenierio de software','Soy estudiante','Coca cola','Desarrollar','Gobierno nacional','Desarrollar','Nasa','Desarrollar','Uniempri','Ingeniero','Sena','Adminis','Parroco','Bachi','Español','Ingles','Frances','Sotfware','Muchos','Ser yo');
INSERT INTO `datacenterhrplus`.`Candidatos`(`Id`, `nombre`, `apellido`, `cedula`, `telefono`, `correo`, `direccion`, `perfil`, `sobreMi`, `nEU`, `fEU`, `nEP`, `fEP`, `nEA`, `fEA`, `nIU`, `tIU`, `nIP`, `tIP`, `nIA`, `tIA`, `idiomaN`, `idiomaEP`, `idiomaES`, `conocimientos`, `intereses`, `habilidades`) VALUES (2,'Richard','Deiby',987654321,31336925,'richard@gmail.com','calle falsa 456','Ingenierio de software','Soy estudiante','Coca cola','Desarrollar','Gobierno nacional','Desarrollar','Nasa','Desarrollar','Uniempri','Ingeniero','Sena','Adminis','Parroco','Bachi','Español','Ingles','Frances','Sotfware','Muchos','Ser yo');*/
